import Header from '@/components/header'
import '@/styles/globals.css'
import { Toaster } from '@/components/ui/toaster'

// TODO: add suspense for every page and high latency component so only that component show loading while the rest is visible

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Toaster />
      </body>
    </html>
  )
}
