import '@/styles/globals.css'
import { LocalStorageCleaner } from '@/components/LocalStorageCleaner'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <LocalStorageCleaner />
        {children}
      </body>
    </html>
  );
}
